// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/liveops-variants/IntelTimeline.tsx": () => import("../components/mockups/liveops-variants/IntelTimeline.tsx"),
  "./components/mockups/liveops-variants/SectorMatrix.tsx": () => import("../components/mockups/liveops-variants/SectorMatrix.tsx"),
  "./components/mockups/liveops-variants/ThreatDominance.tsx": () => import("../components/mockups/liveops-variants/ThreatDominance.tsx")
};
